# Generated by Django 3.0.5 on 2020-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
