# Generated by Django 3.0.5 on 2020-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('creatdts', models.DateTimeField(auto_now_add=True)),
                ('modifiedts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
    ]
